const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const supabase = require("../config/supabase");

/**
 * Safely writes a section title in the PDF.
 */
const addSectionTitle = (doc, title) => {
  doc.moveDown(1);
  doc.fontSize(15).font("Helvetica-Bold").text(title);
  doc.moveDown(0.4);
};

/**
 * Safely writes bullet list in the PDF.
 */
const addBulletList = (doc, items = []) => {
  if (!Array.isArray(items) || items.length === 0) {
    doc.fontSize(11).font("Helvetica").text("No data available.");
    return;
  }

  items.forEach((item) => {
    doc.fontSize(11).font("Helvetica").text(`• ${item}`, {
      indent: 15,
    });
  });
};

/**
 * Generate final SEO report PDF for an approved task.
 */
const generateFinalReport = async ({ taskId, generated_by }) => {
  // 1. Find task
  const { data: task, error: taskError } = await supabase
    .from("tasks")
    .select("*")
    .eq("id", taskId)
    .single();

  if (taskError || !task) {
    throw new Error("Task not found.");
  }

  // 2. Report can only be generated after approval
  if (task.status !== "approved") {
    throw new Error("Task must be approved before generating final report.");
  }

  // 3. Get latest agent output
  const { data: latestOutput, error: outputError } = await supabase
    .from("agent_outputs")
    .select("*")
    .eq("task_id", taskId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (outputError) {
    throw new Error(outputError.message);
  }

  if (!latestOutput) {
    throw new Error("No agent output found for this task.");
  }

  // 4. Get latest approved review
  const { data: latestReview, error: reviewError } = await supabase
    .from("reviews")
    .select("*")
    .eq("task_id", taskId)
    .eq("decision", "approved")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (reviewError) {
    throw new Error(reviewError.message);
  }

  if (!latestReview) {
    throw new Error("No approved review found for this task.");
  }

  // 5. Prepare reports folder
  const reportsDir = path.join(__dirname, "../../reports");

  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const pdfFileName = `seo-report-${taskId}.pdf`;
  const pdfFilePath = path.join(reportsDir, pdfFileName);

  const output = latestOutput.output_content || {};

  // 6. Generate PDF
  const doc = new PDFDocument({
    margin: 50,
    size: "A4",
  });

  const stream = fs.createWriteStream(pdfFilePath);
  doc.pipe(stream);

  doc.fontSize(20).font("Helvetica-Bold").text("RND Technosoft AI Agent Report", {
    align: "center",
  });

  doc.moveDown(0.5);
  doc.fontSize(13).font("Helvetica").text("SEO Department Final Report", {
    align: "center",
  });

  doc.moveDown(1.5);

  addSectionTitle(doc, "Task Details");
  doc.fontSize(11).font("Helvetica").text(`Task Title: ${task.title}`);
  doc.text(`Priority: ${task.priority}`);
  doc.text(`Final Status: finalized`);
  doc.text(`Created By: ${task.created_by || "CEO"}`);
  doc.text(`Generated By: ${generated_by || "CEO"}`);
  doc.text(`Generated At: ${new Date().toLocaleString()}`);

  addSectionTitle(doc, "Task Description");
  doc.fontSize(11).font("Helvetica").text(task.description || "No description available.");

  addSectionTitle(doc, "SEO Summary");
  doc.fontSize(11).font("Helvetica").text(output.seo_summary || "No summary available.");

  addSectionTitle(doc, "Target Keywords");
  addBulletList(doc, output.target_keywords);

  addSectionTitle(doc, "On-Page SEO Suggestions");
  addBulletList(doc, output.on_page_suggestions);

  addSectionTitle(doc, "Technical SEO Suggestions");
  addBulletList(doc, output.technical_seo_suggestions);

  addSectionTitle(doc, "Content Strategy");
  addBulletList(doc, output.content_strategy);

  addSectionTitle(doc, "AEO Suggestions");
  addBulletList(doc, output.aeo_suggestions);

  addSectionTitle(doc, "GEO Suggestions");
  addBulletList(doc, output.geo_suggestions);

  addSectionTitle(doc, "LLM Optimization Suggestions");
  addBulletList(doc, output.llm_optimization_suggestions);

  addSectionTitle(doc, "Next Steps");
  addBulletList(doc, output.next_steps);

  addSectionTitle(doc, "CEO Review");
  doc.fontSize(11).font("Helvetica").text(`Decision: ${latestReview.decision}`);
  doc.text(`Feedback: ${latestReview.feedback || "No feedback provided."}`);

  doc.moveDown(2);
  doc
    .fontSize(10)
    .font("Helvetica-Oblique")
    .text("Generated by RND Technosoft AI Agent System", {
      align: "center",
    });

  doc.end();

  await new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  // 7. Save report record
  const reportContent = {
    task,
    latest_output: latestOutput,
    latest_review: latestReview,
  };

  const { data: report, error: reportError } = await supabase
    .from("reports")
    .insert([
      {
        task_id: taskId,
        report_title: `SEO Final Report - ${task.title}`,
        report_content: reportContent,
        pdf_file_name: pdfFileName,
        pdf_file_path: pdfFilePath,
        status: "generated",
        generated_by: generated_by || "CEO",
      },
    ])
    .select()
    .single();

  if (reportError) {
    throw new Error(reportError.message);
  }

  // 8. Update task status to finalized
  const { data: updatedTask, error: taskUpdateError } = await supabase
    .from("tasks")
    .update({
      status: "finalized",
      updated_at: new Date().toISOString(),
    })
    .eq("id", taskId)
    .select()
    .single();

  if (taskUpdateError) {
    throw new Error(taskUpdateError.message);
  }

  // 9. Add status log
  const { error: logError } = await supabase.from("task_status_logs").insert([
    {
      task_id: taskId,
      old_status: "approved",
      new_status: "finalized",
      changed_by: generated_by || "CEO",
      note: "Final PDF report generated.",
    },
  ]);

  if (logError) {
    throw new Error(logError.message);
  }

  return {
    task: updatedTask,
    report,
  };
};

/**
 * Get latest report PDF path for download.
 */
const getReportForDownload = async (taskId) => {
  const { data: report, error } = await supabase
    .from("reports")
    .select("*")
    .eq("task_id", taskId)
    .order("generated_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(error.message);
  }

  if (!report) {
    throw new Error("No report found for this task.");
  }

  if (!report.pdf_file_path || !fs.existsSync(report.pdf_file_path)) {
    throw new Error("PDF file not found on server.");
  }

  return report;
};

module.exports = {
  generateFinalReport,
  getReportForDownload,
};